#!/usr/bin/env bash
#
# Refresh `docs/api/` from a checkout of the private studio repository.
#
# The API documents have exactly one source of truth — `fieldwork-group/course-studio`
# — and this kit is a *projection* of them. Nothing flows the other way: an edit
# made here is lost on the next sync, which is why every synced file says so in
# the private repo and why this script never writes back.
#
#   tools/sync-from-studio.sh ../course-studio          # copy, then show the diff
#   tools/sync-from-studio.sh ../course-studio --check   # exit 1 if the kit is behind
#
# `--check` is what a CI step in the private repo runs against a clone of the
# kit: it copies nothing and fails when a document has moved on without the kit.
#
# Before it copies, it greps the incoming bytes for the things that must never
# reach a public repository (the rule in the batch's common rules: no lecturer's
# name, no student URL, no infrastructure name). A hit stops the sync; it does
# not quietly scrub, because a scrubbed document is no longer the document the
# private repo `--check`s against, and a difference nobody can see is worse than
# a refusal somebody must answer.

set -euo pipefail

STUDIO=${1:-}
MODE=${2:-copy}
KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ -z "$STUDIO" ] || [ ! -d "$STUDIO" ]; then
  echo "usage: tools/sync-from-studio.sh <path-to-course-studio-checkout> [--check]" >&2
  exit 2
fi
STUDIO="$(cd "$STUDIO" && pwd)"

# source → destination, relative to the two roots.
FILES=(
  "docs/api/agent-guide.md:docs/api/agent-guide.md"
  "docs/api/guide.md:docs/api/guide.md"
  "docs/api/vocabulary.md:docs/api/vocabulary.md"
  "docs/api/lecture.schema.json:docs/api/lecture.schema.json"
  "docs/api/course.schema.json:docs/api/course.schema.json"
  "studio/api/openapi.yaml:docs/api/openapi.yaml"
)

# What may not cross the fence. Case-insensitive, extended regular expressions.
# Add a name here the day it exists rather than the day it leaks.
FORBIDDEN='frishman|amazoncognito\.com|cognito-idp\.[a-z0-9-]+\.amazonaws\.com|s3\.[a-z0-9-]+\.amazonaws\.com|arn:aws:|cloudfront\.net|AKIA[0-9A-Z]{16}|cst_[A-Za-z0-9]'

fail=0

for pair in "${FILES[@]}"; do
  src="$STUDIO/${pair%%:*}"
  dst="$KIT/${pair##*:}"
  if [ ! -f "$src" ]; then
    echo "missing in the studio checkout: ${pair%%:*}" >&2
    fail=1
    continue
  fi
  if grep -nEi "$FORBIDDEN" "$src" >/dev/null; then
    echo "REFUSED ${pair%%:*} — it carries something that stays private:" >&2
    grep -nEi "$FORBIDDEN" "$src" >&2
    fail=1
    continue
  fi
  if [ "$MODE" = "--check" ]; then
    if ! diff -q "$src" "$dst" >/dev/null 2>&1; then
      echo "behind: ${pair##*:}" >&2
      diff -u "$dst" "$src" | head -40 >&2 || true
      fail=1
    fi
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "synced ${pair##*:}"
  fi
done

# `AGENTS.md` at the root is the agent guide with a short preamble: an agent
# that walks into a repository reads `AGENTS.md` by convention, and a second,
# drifting copy of the guide would be worse than none. Generated here so there
# is nothing for anyone to remember.
agents_tmp="$(mktemp)"
{
  cat <<'HEADER'
<!-- Generated by tools/sync-from-studio.sh from docs/api/agent-guide.md. Do not edit. -->

> **Read this first if you are an agent.** It is a copy of
> [`docs/api/agent-guide.md`](docs/api/agent-guide.md), synced from the studio
> itself. The other half of the kit is the demo format your figures must meet:
> [`docs/demos/format.md`](docs/demos/format.md), built with
> [`docs/demos/authoring.md`](docs/demos/authoring.md).

HEADER
  cat "$STUDIO/docs/api/agent-guide.md"
} > "$agents_tmp"

if [ "$MODE" = "--check" ]; then
  if ! diff -q "$agents_tmp" "$KIT/AGENTS.md" >/dev/null 2>&1; then
    echo "behind: AGENTS.md" >&2
    fail=1
  fi
else
  cp "$agents_tmp" "$KIT/AGENTS.md"
  echo "synced AGENTS.md"
fi
rm -f "$agents_tmp"

if [ "$fail" -ne 0 ]; then exit 1; fi

if [ "$MODE" != "--check" ]; then
  echo
  echo "--- git status in the kit ---"
  git -C "$KIT" status --short -- docs/api || true
  echo
  echo "Read the diff before committing. The kit is public; these documents are"
  echo "the only thing in it that somebody else wrote."
fi
